#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangfire.SignalRViewer.Templater.Pages
{
    using System;
    using System.Collections.Generic;
    
    #line 3 "..\..\Pages\LogViewer.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    using System.Text;
    
    #line 4 "..\..\Pages\LogViewer.cshtml"
    using Hangfire.Dashboard.Pages;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class LogViewer : Hangfire.Dashboard.RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n\r\n");





            
            #line 6 "..\..\Pages\LogViewer.cshtml"
  
    Layout = new LayoutPage("Hello World");


            
            #line default
            #line hidden
WriteLiteral(@"
<link rel=""stylesheet"" type=""text/css"" href=""/css/styles.css""/>

<script type=""application/javascript"" src=""/libs/signalr.js""></script>
<script type=""application/javascript"" src=""/js/index.js""></script>

<div class=""row"">
    <div class=""col-12"">
        <ul id=""messagesList""></ul>
    </div>
</div>");


        }
    }
}
#pragma warning restore 1591
