name: Publish Nuget package

on: 
  release:
    types: [published]
    
jobs:
  build-test-pack:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
        
    - name: Restore dependencies
      run: dotnet restore ./Hangfire.SignalRViewer/Hangfire.SignalRViewer.csproj
      
    - name: Pack
      run: dotnet pack ./Hangfire.LogViewer/Hangfire.SignalRViewer/Hangfire.SignalRViewer.csproj --output nupkgs -p:PackageVersion=${{ github.event.release.tag_name }}
      
    - name: Push
      run: dotnet nuget push ./nupkgs/Hangfire.SignalRViewer.${{ github.event.release.tag_name }}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
      
